// Trinity-Vue/src/Fields/BaseField.vue
<template>
  <div class="field col-12 md:col" :class="containerClass">
    <label :for="component.columnName">{{ component.label }}</label>
    <div
      :class="{
        'p-inputgroup':
          component.prefixes ||
          component.suffixes ||
          component.prefixIcons ||
          component.suffixIcons,
      }"
    >
      <span
        class="p-inputgroup-addon"
        v-for="(p, index) of component.prefixIcons"
        :key="`${index}_${p}`"
      >
        <i :class="p"></i>
      </span>
      <span
        class="p-inputgroup-addon"
        v-for="(p, index) of component.prefixes"
        :key="`${index}_${p}`"
      >
        {{ p }}
      </span>

      <component
        :is="is"
        v-bind="attrs"
        :id="component.columnName"
        :name="component.columnName"
        :modelValue="form.data()[component.columnName]"
        @update:modelValue="
          (value) => setFieldValue(component.columnName, value)
        "
        v-tooltip.top.focus="component.toolTip"
        :disabled="component.disabled"
        :placeholder="component.placeholder"
        type="text"
        :class="{ 'p-invalid': errors?.value[component.columnName] }"
        :form="form"
        :errors="errors"
      />

      <span
        class="p-inputgroup-addon"
        v-for="(p, index) of component.suffixIcons"
        :key="`${index}_${p}`"
      >
        <i :class="p"></i>
      </span>
      <span
        class="p-inputgroup-addon"
        v-for="(p, index) of component.suffixes"
        :key="`${index}_${p}`"
      >
        {{ p }}
      </span>
    </div>
    <small :id="`${component.columnName}-help`">
      {{ component.helperText }}
    </small>
    <div
      :id="`${component.columnName}-error`"
      class="p-error mt-1"
      v-if="errors?.value[component.columnName]"
    >
      <div
        v-for="(err, index) of errors?.value[component.columnName]"
        :key="index"
      >
        {{ err }}
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import ComponentProps from "@/Types/ComponentProps";
import type Field from "@/Types/Field";

defineProps<ComponentProps<Field>>();
</script>

<style scoped></style>

// Trinity-React/src/fields/BaseFieldComponent.tsx
import React from 'react';
import { classNames } from 'primereact/utils';
import BaseField from '@/types/Models/Fields/BaseField';
import { Errors, ErrorBag } from '@inertiajs/core/types/types';

const BaseFieldComponent = ({ component, errors, children }: { component: BaseField; errors: Errors & ErrorBag; children?: React.ReactNode }) => {
    if (component.hidden) return <></>;

    return (
        <div className={classNames(['field col-12 md:col', component.columnSpan > 0 && component.columnSpan < 12 ? `md:col-${component.columnSpan}` : ''])}>
            <label htmlFor={component.columnName}>{component.label}</label>

            <div className={component.prefixes || component.suffixes || component.prefixIcons || component.suffixIcons ? 'p-inputgroup' : ''}>
                {component.prefixIcons?.map((icon, index) => (
                    <span
                        className="p-inputgroup-addon"
                        key={`${index}_${icon}`}
                    >
                        <i className={icon}></i>
                    </span>
                ))}

                {component.prefixes?.map((p, index) => (
                    <span
                        className="p-inputgroup-addon"
                        key={`${index}_${p}`}
                    >
                        {p}
                    </span>
                ))}

                {children}

                {component.suffixIcons?.map((icon, index) => (
                    <span
                        className="p-inputgroup-addon"
                        key={`${index}_${icon}`}
                    >
                        <i className={icon}></i>
                    </span>
                ))}

                {component.suffixes?.map((s, index) => (
                    <span
                        className="p-inputgroup-addon"
                        key={`${index}_${s}`}
                    >
                        {s}
                    </span>
                ))}
            </div>

            <small id={`${component.columnName}-help`}>{component.helperText}</small>

            {errors[component.columnName] && (
                <div className="p-error mt-1">
                    <span className="flex">{errors[component.columnName]}</span>
                </div>
            )}
        </div>
    );
};

export default BaseFieldComponent;
