// Trinity-Vue/src/Fields/BelongsToField.vue
<template>
  <SelectInputField
    :component="props.component"
    :form="form"
    :errors="errors"
    :setFieldValue="setFieldValue"
    :search="fetchAssociates"
    :disabled="fetching"
    :loading="fetching"
  />
</template>

<script lang="ts" setup>
import type FieldProps from "@/Types/Props/FieldProps";
import type SelectField from "@/Types/Models/SelectField";
import { ref } from "vue";
import axios from "axios";
import { useConfigStore } from "@/Stores/ConfigStore";
import { usePageProps } from "@/Composables/trinity_page_props";

const configStore = useConfigStore();
const pageProps = usePageProps();
const props = defineProps<FieldProps<SelectField>>();

const fetching = ref(false);
async function fetchAssociates(
  search: string
): Promise<Array<{ [key: string]: string }>> {
  fetching.value = true;

  const res = await axios
    .get(
      `/${configStore.configs.prefix}/${pageProps.value.resource?.name}/relationship`,
      {
        params: {
          column: props.component.columnName,
          search,
        },
      }
    )
    .then((res) => res.data);
  fetching.value = false;

  return [];
}
</script>

<style scoped></style>

// Trinity-React/src/fields/BelongsToField.tsx
import React, { useLayoutEffect, useState } from 'react';
import FieldProps from '@/Types/Props/FieldProps';
import SelectInputField from '@/fields/SelectInputField';
import axios from 'axios';
import { useConfigs } from '@/hooks/trinity_configs';
import usePageProps from '@/hooks/trinity_page_props';
import { SelectItemOptionsType } from 'primereact/selectitem';
import RelationshipField from '@/Types/Models/RelationshipField';
import { VirtualScrollerLazyParams } from 'primereact/virtualscroller';
import last from 'lodash/last';

const BelongsToField = (props: FieldProps<RelationshipField>) => {
    const { component, errors, formData, setFieldValue } = props;
    const configs = useConfigs();
    const { resource, data } = usePageProps<any>();
    const [options, setOptions] = useState<SelectItemOptionsType>([]);

    let relation = data;
    for (const r of component.relationshipName?.split('.') ?? []) {
        if (relation && relation[r]) relation = relation[r];
    }

    async function fetchAssociates(e: (VirtualScrollerLazyParams & { filter: string }) | null): Promise<SelectItemOptionsType> {
        const res = await axios
            .get(`/${configs.prefix}/${resource?.name}/relationship`, {
                params: {
                    column: component.columnName,
                    search: e?.filter
                }
            })
            .then((res) => res.data);

        return res ?? [];
    }

    useLayoutEffect(() => {
        if (!component.lazy)
            fetchAssociates(null).then((opts) => {
                setOptions(opts);
                console.log(opts);
            });
    }, [component]);

    return (
        <SelectInputField
            component={component}
            errors={errors}
            search={fetchAssociates}
            lazy={component.lazy}
            formData={formData}
            setFieldValue={setFieldValue}
            options={options}
            value={relation ? relation[last(component.foreignColumn?.split('.'))!].toString() : undefined}
        />
    );
};

export default BelongsToField;
