// Trinity-Vue/src/Fields/IdField.vue
<template>
  <TextField
    :component="props.component"
    :form="form"
    :errors="errors"
    :setFieldValue="setFieldValue"
  />
</template>

<script lang="ts" setup>
import type FieldProps from "@/Types/Props/FieldProps";
import type BaseField from "@/Types/Models/BaseField";

const props = defineProps<FieldProps<BaseField>>();
</script>

<style scoped></style>

// Trinity-React/src/fields/IdField.tsx
import React from 'react';
import FieldProps from '@/Types/Props/FieldProps';
import BaseField from '@/Types/Models/BaseField';
import TextField from '@/fields/TextField';

const IdField = ({ component, errors, form }: FieldProps<BaseField>) => {
    return (
        <TextField
            component={component}
            form={form}
            errors={errors}
        />
    );
};

export default IdField;
