// Trinity-Vue/src/Fields/TextAreaField.vue
<template>
  <BaseFieldComponent :component="props.component" :errors="errors">
    <TextArea
      :id="props.component.columnName"
      :name="props.component.columnName"
      :modelValue="form.data()[props.component.columnName]"
      @update:modelValue="
        (value) => setFieldValue(props.component.columnName, value)
      "
      v-tooltip.top.focus="props.component.toolTip"
      :disabled="props.component.disabled"
      :placeholder="props.component.placeholder"
      type="text"
      :class="{
        'p-invalid': errors?.value[props.component.columnName],
      }"
      :autoResize="props.component.autoResize"
      :rows="props.component.rows"
      :cols="props.component.cols"
    />
  </BaseFieldComponent>
</template>

<script lang="ts" setup>
import TextArea from "primevue/textarea";
import BaseFieldComponent from "@/Fields/BaseFieldComponent.vue";
import type TextAreaField from "@/Types/Models/TextAreaField";
import type FieldProps from "@/Types/Props/FieldProps";

const props = defineProps<FieldProps<TextAreaField>>();
</script>

<style scoped></style>

// Trinity-React/src/fields/TextAreaField.tsx
import React from 'react';
import BaseFieldComponent from '@/fields/BaseFieldComponent';
import { classNames } from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import FieldProps from "@/types/Props/Fields/FieldProps";
import TextAreaField from '@/types/Models/Fields/TextAreaField';

const TextAreaField = ({ component, formData, setFieldValue, errors }: FieldProps<TextAreaField>) => {
    return (
        <BaseFieldComponent
            component={component}
            errors={errors}
        >
            <InputTextarea
                id={component.columnName}
                name={component.columnName}
                disabled={component.disabled}
                hidden={component.hidden}
                placeholder={component.placeholder}
                className={classNames({ 'p-invalid': errors?.value[component.columnName] })}
                tooltip={component.tooltip}
                tooltipOptions={{ event: 'focus', position: 'top' }}
                autoResize={component.autoResize}
                rows={component.rows}
                cols={component.cols}
                value={formData[component.columnName]}
                onChange={(event) => setFieldValue(component.columnName, event.target.value)}
            />
        </BaseFieldComponent>
    );
};

export default TextAreaField;
