// Trinity-Vue/src/Fields/TextField.vue
<template>
  <BaseFieldComponent :component="props.component" :errors="errors">
    <InputText
      :id="props.component.columnName"
      :name="props.component.columnName"
      :modelValue="form.data()[props.component.columnName]"
      @update:modelValue="
        (value) => props.setFieldValue(props.component.columnName, value)
      "
      v-tooltip.top.focus="props.component.toolTip"
      :disabled="props.component.disabled"
      :placeholder="props.component.placeholder"
      type="text"
      :class="{ 'p-invalid': errors?.value[props.component.columnName] }"
    />
  </BaseFieldComponent>
</template>

<script lang="ts" setup>
import InputText from "primevue/inputtext";
import BaseFieldComponent from "@/Fields/BaseFieldComponent.vue";
import type FieldProps from "@/Types/Props/FieldProps";
import type BaseField from "@/Types/Models/BaseField";

const props = defineProps<FieldProps<BaseField>>();
</script>

<style scoped></style>

// Trinity-React/src/fields/TextField.tsx
import React, { useState } from 'react';
import BaseFieldComponent from '@/fields/BaseFieldComponent';
import { InputText } from 'primereact/inputtext';
import { classNames } from 'primereact/utils';
import FieldProps from '@/types/Props/Fields/FieldProps';
import BaseField from '@/types/Models/Fields/BaseField';

const TextField = ({ component, formData, setFieldValue, errors }: FieldProps<BaseField>) => {
    const [value, setValue] = useState(formData[component.columnName] ?? '');
    return (
        <BaseFieldComponent
            component={component}
            errors={errors}
        >
            <InputText
                id={component.columnName}
                name={component.columnName}
                disabled={component.disabled}
                hidden={component.hidden}
                placeholder={component.placeholder}
                className={classNames({ 'p-invalid': errors?.value[component.columnName] })}
                tooltip={component.tooltip}
                tooltipOptions={{ event: 'focus', position: 'top' }}
                value={value}
                onChange={(event) => {
                    setValue(event.target.value);
                    setFieldValue(component.columnName, event.target.value);
                }}
            />
        </BaseFieldComponent>
    );
};

export default TextField;
