// Trinity-React/src/pages/Create.tsx
import React, { useContext, useState } from 'react';
import usePageProps from '@/hooks/trinity_page_props';
import { Head } from '@/components/Head';
import { Button } from 'primereact/button';
import { Toolbar } from 'primereact/toolbar';
import { useConfigs } from '@/hooks/trinity_configs';
import { trinityLink } from '@/utilities/trinity_link';
import { AppContext } from '@/contexts/AppContext';
import { useForm } from '@inertiajs/inertia-react';
import { useTrinityFields } from '@/hooks/trinity_resource_fields';
import last from 'lodash/last';

const Create = () => {
    const config = useConfigs();
    const { resource, errors } = usePageProps();
    const fields = useTrinityFields();
    const { components } = useContext(AppContext);
    const [createAddAnother, setCreateAddAnother] = useState(false);

    const data = {} as any;
    for (const field of fields) {
        data[last(field.columnName.split('.'))!] = undefined;
    }
    const form = useForm(resource!.name, data);

    const create = (_createAddAnother: boolean = false) => {
        setCreateAddAnother(_createAddAnother);

        form.post('', {
            preserveScroll: true,
            preserveState: true
        });
    };

    const toolbarRight = (
        <div className="grid">
            <Button
                label="Create"
                className="m-2 p-button-primary"
                disabled={form.processing}
                loading={form.processing && !createAddAnother}
                onClick={() => create(false)}
            />
            <Button
                label="Create & create another"
                className="m-2 p-button-help"
                disabled={form.processing}
                loading={form.processing && createAddAnother}
                onClick={() => create(true)}
            />
            <Button
                label="Cancel"
                className="m-2 p-button-secondary"
                onClick={() => trinityLink(`/${config.prefix}/${resource?.name}`)}
            />
        </div>
    );

    return (
        <>
            <Head title={resource?.pluralLabel}></Head>

            <div className="card">
                <h5 className="mb-6">Create {resource?.pluralLabel}</h5>

                <form className="p-fluid formgrid grid col-12">
                    {resource?.schema.map((component, index) =>
                        components?.has(component.componentName) ? (
                            components?.get(component.componentName)!({
                                key: `form_${index}_${component.componentName}`,
                                component,
                                form,
                                errors
                            })
                        ) : (
                            <div key={`form_${index}_${component.componentName}`}></div>
                        )
                    )}
                </form>

                <div className="grid">
                    <div className="field">
                        {errors?.value[''] && (
                            <small className="p-error">
                                {errors?.value[''].map((e, index) => (
                                    <span
                                        className="flex"
                                        key={index}
                                    >
                                        {e}
                                    </span>
                                ))}
                            </small>
                        )}
                    </div>
                </div>

                <div className="mt-3">
                    <Toolbar right={toolbarRight} />
                </div>
            </div>
        </>
    );
};

export default Create;

// Trinity-Vue/src/Pages/Create.vue
<template>
  <AppHead :title="pageProps.resource?.pluralLabel"></AppHead>

  <div class="grid">
    <div class="col-12">
      <div class="card">
        <h5 class="mb-6">Create {{ pageProps.resource?.pluralLabel }}</h5>

        <form class="p-fluid formgrid grid col-12">
          <template
            v-for="(component, index) of pageProps.resource?.schema"
            :key="`form_${index}_${component.componentName}`"
          >
            <component
              :is="component.componentName"
              :component="component"
              :form="form"
              :errors="pageProps.errors"
              :setFieldValue="setFieldValue"
              class="mb-4"
            />
          </template>
        </form>

        <div class="grid">
          <div class="field">
            <div class="p-error" v-if="pageProps.errors?.value['']">
              <div
                v-for="(err, index) of pageProps.errors?.value['']"
                :key="index"
              >
                {{ err }}
              </div>
            </div>
          </div>
        </div>

        <div class="mt-3">
          <Toolbar disabled>
            <template #start>
              <div class="grid">
                <Button
                  label="Create"
                  class="m-2 p-button-primary"
                  @click="() => create()"
                  :disabled="form.processing"
                  :loading="!addAnother && form.processing"
                />
                <Button
                  label="Create & create another"
                  class="m-2 p-button-help"
                  @click="() => create(true)"
                  :disabled="form.processing"
                  :loading="addAnother && form.processing"
                />
                <Button
                  label="Cancel"
                  class="m-2 p-button-secondary"
                  @click="useTrinityLink(`/${pageProps.resource?.name}`)"
                  :disabled="form.processing"
                />
              </div>
            </template>
          </Toolbar>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { useForm } from "@inertiajs/inertia-vue3";
import { usePageProps } from "@/Composables/trinity_page_props";
import { useTrinityLink } from "@/Composables/trinity_link";
import Toolbar from "primevue/toolbar";
import Button from "primevue/button";
import { ref } from "vue";
import { useGetResourceFields } from "@/Composables/trinity_resource_fields";

const pageProps = usePageProps();
const fields = useGetResourceFields();
const data = {} as any;
for (const field of fields) {
  data[field.columnName] = null;
}
const form = useForm(data);
const addAnother = ref(false);

function setFieldValue(attr: string, value: any) {
  form.defaults({ ...form.data(), ...{ [attr]: !value ? null : value } });
}

function create(createAddAnother: boolean = false) {
  addAnother.value = createAddAnother;
  form.reset();
  form.post("", {
    preserveScroll: true,
    preserveState: true,
  });
}
</script>
