// Trinity-React/src/pages/Login.tsx
import React, { useContext, useState } from 'react';
import usePageProps from '@/hooks/trinity_page_props';
import { Head } from '@/components/Head';
import { Button } from 'primereact/button';
import { Checkbox } from 'primereact/checkbox';
import { Password } from 'primereact/password';
import { InputText } from 'primereact/inputtext';
import { classNames } from 'primereact/utils';
import { LayoutContext } from '@/contexts/LayoutContext';
import { useLogo } from '@/hooks/trinity_logo';
import { useConfigs } from '@/hooks/trinity_configs';
import { useForm } from '@inertiajs/inertia-react';
import { Method } from '@inertiajs/inertia';

const Login = () => {
    const configs = useConfigs();
    const pageProps = usePageProps();
    const [password, setPassword] = useState('');
    const [checked, setChecked] = useState(false);
    const { layoutConfig } = useContext(LayoutContext);
    const logo = useLogo();
    const containerClassName = classNames('surface-ground flex align-items-center justify-content-center min-h-screen min-w-screen overflow-hidden', { 'p-input-filled': layoutConfig.inputStyle === 'filled' });

    const { data, setData, submit, processing } = useForm({
        email: '',
        password: '',
        remember: false
    });

    return (
        <>
            <Head />

            <div className={containerClassName}>
                <div className="flex flex-column align-items-center justify-content-center">
                    <img
                        src={logo}
                        alt={configs.title}
                        className="mb-5 w-6rem flex-shrink-0"
                    />
                    <div
                        style={{
                            borderRadius: '56px',
                            padding: '0.3rem',
                            background: 'linear-gradient(180deg, var(--primary-color) 10%, rgba(33, 150, 243, 0) 30%)'
                        }}
                    >
                        <form
                            className="w-full surface-card py-8 px-5 sm:px-8"
                            style={{ borderRadius: '53px' }}
                            onSubmit={(e) => {
                                e.preventDefault();
                                submit(Method.POST, '');
                            }}
                        >
                            <div>
                                <div className="field">
                                    <label
                                        htmlFor="email1"
                                        className="block text-900 text-xl font-medium mb-2"
                                    >
                                        Email
                                    </label>
                                    <InputText
                                        type="email"
                                        required
                                        placeholder="Email address"
                                        className={classNames('w-full md:w-30rem mb-3', { 'p-invalid': pageProps.errors?.value['Email'] })}
                                        value={data.email}
                                        onChange={(e) => setData('email', e.target.value)}
                                        style={{ padding: '1rem' }}
                                    />
                                    {pageProps.errors?.value['Email'] && (
                                        <small className="p-error w-full block md:w-30rem">
                                            {pageProps.errors?.value['Email'].map((e, index) => (
                                                <span
                                                    className="flex"
                                                    key={index}
                                                >
                                                    {e}
                                                </span>
                                            ))}
                                        </small>
                                    )}
                                </div>
                                <div className="field">
                                    <label className="block text-900 font-medium text-xl mb-2">Password</label>
                                    <Password
                                        value={password}
                                        onChange={(e) => {
                                            setPassword(e.target.value);
                                            setData('password', e.target.value);
                                        }}
                                        placeholder="Password"
                                        type="password"
                                        required
                                        toggleMask
                                        className={classNames('w-full mb-3', { 'p-invalid': pageProps.errors?.value['Password'] })}
                                        inputClassName="w-full p-3 md:w-30rem"
                                    />
                                    {pageProps.errors?.value['Password'] && (
                                        <small className="p-error w-full block md:w-30rem">
                                            {pageProps.errors?.value['Password'].map((e, index) => (
                                                <span
                                                    className="flex"
                                                    key={index}
                                                >
                                                    {e}
                                                </span>
                                            ))}
                                        </small>
                                    )}
                                </div>
                                <div className="flex align-items-center justify-content-between mb-5 gap-5">
                                    <div className="flex align-items-center">
                                        <Checkbox
                                            checked={checked}
                                            onChange={(e) => {
                                                setChecked(e.checked);
                                                setData('remember', e.checked);
                                            }}
                                            className="mr-2"
                                        />
                                        <label htmlFor="rememberme1">Remember me</label>
                                    </div>
                                    <a
                                        className="font-medium no-underline ml-2 text-right cursor-pointer"
                                        style={{ color: 'var(--primary-color)' }}
                                    >
                                        Forgot password?
                                    </a>
                                </div>
                                <div className="field">
                                    {pageProps.errors?.value[''] && (
                                        <small className="p-error w-full block md:w-30rem">
                                            {pageProps.errors?.value[''].map((e, index) => (
                                                <span
                                                    className="flex"
                                                    key={index}
                                                >
                                                    {e}
                                                </span>
                                            ))}
                                        </small>
                                    )}
                                </div>

                                <Button
                                    label="Sign In"
                                    className="w-full p-3 text-xl"
                                    type="submit"
                                    loading={processing}
                                    disabled={processing}
                                />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </>
    );
};

Login.layout = null as any;
export default Login;

// Trinity-Vue/src/Pages/Login.vue
<template>
  <div
    class="surface-0 flex align-items-center justify-content-center min-h-screen min-w-screen overflow-hidden"
  >
    <div class="grid justify-content-center p-2 lg:p-0" style="min-width: 80%">
      <div class="col-12 mt-5 xl:mt-0 text-center">
        <img
          :src="logo"
          alt="Trinity Admin Panel"
          class="mb-5"
          style="width: 81px; height: 60px"
        />
      </div>
      <div
        class="col-12 xl:col-6"
        style="
          border-radius: 56px;
          padding: 0.3rem;
          background: linear-gradient(
            180deg,
            var(--primary-color),
            rgba(33, 150, 243, 0) 30%
          );
        "
      >
        <div
          class="h-full w-full m-0 py-7 px-4"
          style="
            border-radius: 53px;
            background: linear-gradient(
              180deg,
              var(--surface-50) 38.9%,
              var(--surface-0)
            );
          "
        >
          <form @submit.prevent="submit" class="w-full md:w-10 mx-auto">
            <div class="field">
              <label for="email" class="block text-900 text-xl font-medium mb-2"
                >Email</label
              >
              <InputText
                id="email"
                v-model="form.email"
                name="email"
                type="email"
                class="w-full mb-3"
                placeholder="Email"
                style="padding: 1rem"
                :class="{ 'p-invalid': pageProps.errors?.value['Email'] }"
                required
              />
              <div
                id="email-help"
                class="p-error"
                v-if="pageProps.errors?.value['Email']"
              >
                <div
                  v-for="(err, index) of pageProps.errors?.value['Email']"
                  :key="index"
                >
                  {{ err }}
                </div>
              </div>
            </div>

            <div class="field">
              <label
                for="password1"
                class="block text-900 font-medium text-xl mb-2"
                >Password</label
              >
              <Password
                id="password1"
                v-model="form.password"
                name="password"
                placeholder="Password"
                :toggleMask="true"
                class="w-full mb-3"
                inputClass="w-full"
                inputStyle="padding:1rem"
                :class="{ 'p-invalid': pageProps.errors?.value['Password'] }"
                required
              ></Password>
              <div
                id="password-help"
                class="p-error"
                v-if="pageProps.errors?.value['Password']"
              >
                <div
                  v-for="(err, index) of pageProps.errors?.value['Password']"
                  :key="index"
                >
                  {{ err }}
                </div>
              </div>
            </div>

            <div class="flex align-items-center justify-content-between mb-5">
              <div class="flex align-items-center">
                <Checkbox
                  id="rememberMe"
                  v-model="form.remember"
                  :binary="true"
                  name="remember"
                  class="mr-2"
                ></Checkbox>
                <label for="rememberMe">Remember me</label>
              </div>
              <a
                class="font-medium no-underline ml-2 text-right cursor-pointer"
                style="color: var(--primary-color)"
              >
                Forgot password?
              </a>
            </div>

            <div class="field">
              <div class="p-error" v-if="pageProps.errors?.value['']">
                <div
                  v-for="(err, index) of pageProps.errors?.value['']"
                  :key="index"
                >
                  {{ err }}
                </div>
              </div>
            </div>

            <Button
              label="Sign In"
              type="submit"
              class="w-full p-3 text-xl"
              iconPos="right"
              :loading="form.processing"
              :disabled="form.processing"
            ></Button>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { useLogo } from "@/Composables/trinity_logo";
import { useForm } from "@inertiajs/inertia-vue3";

import InputText from "primevue/inputtext";
import Password from "primevue/password";
import Checkbox from "primevue/checkbox";
import Button from "primevue/button";
import { usePageProps } from "@/Composables/trinity_page_props";

const logo = useLogo();
const pageProps = usePageProps();

const form = useForm({
  email: null,
  password: null,
  remember: false,
});

function submit() {
  form.post("");
}
</script>

<script lang="ts">
export default {
  layout: null,
};
</script>
<style scoped>
.pi-eye {
  transform: scale(1.6);
  margin-right: 1rem;
}

.pi-eye-slash {
  transform: scale(1.6);
  margin-right: 1rem;
}
</style>
