// Trinity-Vue/src/Layouts/FieldsetLayout.vue
<template>
  <Fieldset
    class="col-12"
    :class="`md:col-${props.component.columnSpan}`"
    :legend="props.component.label"
    :toggleable="props.component.toggleable"
    :collapsed="props.component.isToggledHiddenByDefault"
  >
    <div class="p-fluid formgrid grid px-0 mx-0 col-12">
      <template
        v-for="(innerComponent, index) of props.component.schema"
        :key="`fieldset_${index}_${innerComponent.componentName}`"
      >
        <component
          :is="innerComponent.componentName"
          :component="innerComponent"
          :containerClass="
            props.component.columns
              ? `md:col-${12 / props.component.columns}`
              : ''
          "
          :form="form"
          :errors="errors"
          :setFieldValue="setFieldValue"
        />
      </template>
    </div>
  </Fieldset>
</template>

<script lang="ts" setup>
import Fieldset from "primevue/fieldset";

import type BaseLayout from "@/Types/Models/BaseLayout";
import type LayoutProps from "@/Types/Props/LayoutProps";
import type BaseField from "@/Types/Models/BaseField";

const props = defineProps<LayoutProps<BaseField | BaseLayout>>();
</script>

<style scoped></style>

// Trinity-React/src/layouts/FieldsetLayout.tsx
import React, { useContext } from 'react';
import { classNames } from 'primereact/utils';
import { AppContext } from '@/contexts/AppContext';
import { Fieldset } from 'primereact/fieldset';
import LayoutProps from '@/types/Props/Layouts/LayoutProps';
import BaseLayout from '@/types/Models/Layouts/BaseLayout';

const FieldsetLayout = ({ configs, resource, component, record, formData, setFieldValue, errors }: LayoutProps<BaseLayout>) => {
    const { components } = useContext(AppContext);

    return (
        <Fieldset
            className={`col-12 md:col-${component.columnSpan}`}
            legend={component.label}
            toggleable={component.toggleable}
            collapsed={component.isToggledHiddenByDefault}
            style={component.style}
        >
            <div className={classNames(['p-fluid grid px-0 mx-0 col-12', component.columnSpan > 0 && component.columnSpan < 12 ? `md:col-${component.columnSpan}` : ''])}>
                {component?.schema.map((innerComponent, index) =>
                    components?.has(innerComponent.componentName) ? (
                        components?.get(innerComponent.componentName)!({
                            key: `fieldset_${index}_${innerComponent.componentName}`,
                            configs: configs,
                            resource: resource,
                            component: innerComponent,
                            record: record,
                            containerClass: component.columns ? `md:col-${12 / component.columns}` : '',
                            formData,
                            setFieldValue,
                            errors
                        })
                    ) : (
                        <div key={`form_${index}_${innerComponent.componentName}`}></div>
                    )
                )}
            </div>
        </Fieldset>
    );
};

export default FieldsetLayout;
