// Trinity-React/src/components/AppFooter.tsx
import { useLogo } from '@/hooks/trinity_logo';
import { useConfigs } from '@/hooks/trinity_configs';

const AppFooter = () => {
    const configs = useConfigs();
    const logo = useLogo();

    return (
        <div className="layout-footer">
            <img
                src={logo}
                alt={configs.title}
                height="20"
                className="mr-2"
            />
            by
            <span className="font-medium ml-2">Abanoub Nassem</span>
        </div>
    );
};

export default AppFooter;

// Trinity-Vue/src/Components/AppFooter.vue
<template>
  <div class="layout-footer">
    <img alt="Logo" :src="logo" height="20" class="mr-2" />
    by
    <span class="font-medium ml-2">Abanoub Nassem</span>
  </div>
</template>

<script lang="ts" setup>
import { useLogo } from "@/Composables/trinity_logo";

const logo = useLogo();
</script>
