// Trinity-React/src/components/AppTopbar.tsx
import React, { forwardRef, useContext, useImperativeHandle, useRef } from 'react';
import { LayoutContext } from '@/contexts/LayoutContext';
import { Link } from '@inertiajs/inertia-react';
import { classNames } from 'primereact/utils';
import { useLogo } from '@/hooks/trinity_logo';
import { useConfigs } from '@/hooks/trinity_configs';
import { Button } from 'primereact/button';
import { Menu } from 'primereact/menu';
import { Inertia } from '@inertiajs/inertia';

const AppTopbar = forwardRef((props, ref) => {
    const configs = useConfigs();
    const logo = useLogo();
    const { layoutConfig, layoutState, onMenuToggle, showProfileSidebar } = useContext(LayoutContext);
    const menubuttonRef = useRef(null);
    const topbarmenuRef = useRef(null);
    const topbarmenubuttonRef = useRef(null);
    const profileMenu = useRef<Menu>(null);

    useImperativeHandle(ref, () => ({
        menubutton: menubuttonRef.current,
        topbarmenu: topbarmenuRef.current,
        topbarmenubutton: topbarmenubuttonRef.current
    }));

    const profileItems = [
        {
            label: 'Profile',
            items: [
                {
                    label: 'Logout',
                    icon: 'pi pi-sign-out',
                    href: '',
                    command: () => {
                        Inertia.post(`/${configs.prefix}/logout`);
                    }
                }
            ]
        }
    ];

    return (
        <div className="layout-topbar">
            <Link href="/">
                <div className="layout-topbar-logo">
                    <>
                        <img
                            src={logo}
                            width="47.22px"
                            height={'35px'}
                            alt={configs?.title}
                        />
                        <span>{configs?.title}</span>
                    </>
                </div>
            </Link>

            <button
                ref={menubuttonRef}
                type="button"
                className="p-link layout-menu-button layout-topbar-button"
                onClick={onMenuToggle}
            >
                <i className="pi pi-bars" />
            </button>

            <button
                ref={topbarmenubuttonRef}
                type="button"
                className="p-link layout-topbar-menu-button layout-topbar-button"
                onClick={showProfileSidebar}
            >
                <i className="pi pi-ellipsis-v" />
            </button>

            <div
                ref={topbarmenuRef}
                className={classNames('layout-topbar-menu', { 'layout-topbar-menu-mobile-active': layoutState.profileSidebarVisible })}
            >
                <Button
                    className="p-link layout-topbar-button"
                    onClick={(e) => profileMenu.current!.toggle(e)}
                >
                    <i className="pi pi-user"></i>
                    <span>Profile</span>
                </Button>
                <Menu
                    ref={profileMenu}
                    popup
                    model={profileItems}
                />
            </div>
        </div>
    );
});

export default AppTopbar;

// Trinity-Vue/src/Components/AppTopbar.vue
<template>
  <div class="layout-topbar">
    <a class="layout-topbar-logo">
      <img alt="Logo" :src="logo" />
      <span>{{ configStore.configs.title }}</span>
    </a>
    <Button
      class="p-link layout-menu-button layout-topbar-button"
      @click="onMenuToggle"
    >
      <i class="pi pi-bars"></i>
    </Button>

    <button
      class="p-link layout-topbar-menu-button layout-topbar-button"
      v-styleclass="{
        selector: '@next',
        enterClass: 'hidden',
        enterActiveClass: 'scalein',
        leaveToClass: 'hidden',
        leaveActiveClass: 'fadeout',
        hideOnOutsideClick: true,
      }"
    >
      <i class="pi pi-ellipsis-v"></i>
    </button>
    <ul class="layout-topbar-menu hidden lg:flex origin-top">
      <li>
        <Button class="p-link layout-topbar-button" @click="toggle">
          <i class="pi pi-user"></i>
          <span>Profile</span>
        </Button>
        <Menu ref="profileMenu" :model="profileItems" :popup="true" />
      </li>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import Button from "primevue/button";
import Menu from "primevue/menu";
import { useConfigStore } from "@/Stores/ConfigStore";
import { useLogo } from "@/Composables/trinity_logo";
import { Inertia } from "@inertiajs/inertia";

const configStore = useConfigStore();

const emit = defineEmits(["menu-toggle", "topbar-menu-toggle"]);

function onMenuToggle(event: Event | undefined) {
  emit("menu-toggle", event);
}

// function onTopbarMenuToggle(event: Event | undefined) {
//   emit("topbar-menu-toggle", event);
// }

const logo = useLogo();

const profileMenu = ref();
const profileItems = ref([
  {
    label: "Profile",
    items: [
      {
        label: "Logout",
        icon: "pi pi-sign-out",
        href: "",
        command: () => {
          Inertia.post(`/${configStore.configs.prefix}/logout`);
        },
      },
    ],
  },
]);

const toggle = (event: Event | any) => {
  profileMenu.value.toggle(event);
};
</script>
