// Trinity-React/src/fields/MaskField.tsx
import React from 'react';
import FieldProps from '@/Types/Props/FieldProps';
import BaseFieldComponent from '@/fields/BaseFieldComponent';
import { classNames } from 'primereact/utils';
import MaskField from '@/Types/Models/MaskField';
import { InputMask } from 'primereact/inputmask';

const MaskField = ({ component, form, errors }: FieldProps<MaskField>) => {
    return (
        <BaseFieldComponent
            component={component}
            errors={errors}
        >
            <InputMask
                id={component.columnName}
                name={component.columnName}
                disabled={component.disabled}
                placeholder={component.placeholder}
                type="text"
                className={classNames({ 'p-invalid': errors?.value[component.columnName] })}
                tooltip={component.toolTip}
                tooltipOptions={{ event: 'focus', position: 'top' }}
                mask={component.inputMask}
                slotChar={component.slotChar ?? '_'}
                autoClear={component.autoClear}
                value={form?.data[component.columnName]}
                onChange={(event) => form?.setData(component.columnName, event.target.value)}
            />
        </BaseFieldComponent>
    );
};

export default MaskField;

// Trinity-Vue/src/Fields/MaskField.vue
<template>
  <BaseFieldComponent :component="props.component" :errors="errors">
    <InputMask
      :id="props.component.columnName"
      :name="props.component.columnName"
      :modelValue="form.data()[props.component.columnName]"
      @update:modelValue="
        (value) => props.setFieldValue(props.component.columnName, value)
      "
      v-tooltip.top.focus="props.component.toolTip"
      :disabled="props.component.disabled"
      :placeholder="props.component.placeholder"
      type="text"
      :class="{ 'p-invalid': errors?.value[props.component.columnName] }"
      :mask="props.component.inputMask"
      :slotChar="props.component.slotChar ?? '_'"
      :autoClear="props.component.autoClear"
    />
  </BaseFieldComponent>
</template>

<script lang="ts" setup>
import InputMask from "primevue/inputmask";

import type MaskField from "@/Types/Models/MaskField";
import type FieldProps from "@/Types/Props/FieldProps";
import BaseFieldComponent from "@/Fields/BaseFieldComponent.vue";

const props = defineProps<FieldProps<MaskField>>();
</script>

<style scoped></style>
