// Trinity-Vue/src/Pages/Index.vue
<template>
  <AppHead :title="resource?.pluralLabel"></AppHead>

  <div class="grid">
    <div class="col-12">
      <div class="card">
        <h5>{{ resource?.pluralLabel }}</h5>
        <Table />
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import Table from "@/Components/Table.vue";
import { usePageProps } from "@/Composables/trinity_page_props";

const pageProps = usePageProps();
const resource = pageProps.value.resource;
</script>

// Trinity-React/src/pages/Index.tsx
import React from 'react';
import usePageProps from '@/hooks/trinity_page_props';
import { Head } from '@/components/Head';
import Table from '@/components/Table';

const Index = () => {
    const { resource } = usePageProps();

    return (
        <>
            <Head title={resource?.pluralLabel}></Head>

            <div className="grid">
                <div className="col-12">
                    <div className="card">
                        <h5>{resource?.pluralLabel}</h5>

                        <Table />
                    </div>
                </div>
            </div>
        </>
    );
};

export default Index;
