// Trinity-React/src/layouts/GridLayout.tsx
import React, { useContext } from 'react';
import { classNames } from 'primereact/utils';
import { AppContext } from '@/contexts/AppContext';
import LayoutProps from '@/types/Props/Layouts/LayoutProps';
import BaseLayout from '@/types/Models/Layouts/BaseLayout';

const GirdLayout = ({ configs, resource, component, record, formData, setFieldValue, errors, style }: LayoutProps<BaseLayout>) => {
    const { components } = useContext(AppContext);

    return (
        <div
            style={style}
            className={classNames(['p-fluid grid px-0 mx-0 col-12', component.columnSpan > 0 && component.columnSpan < 12 ? `md:col-${component.columnSpan}` : ''])}
        >
            {component?.schema.map((innerComponent, index) =>
                components?.has(innerComponent.componentName) ? (
                    components?.get(innerComponent.componentName)!({
                        key: `grid_${index}_${innerComponent.componentName}`,
                        configs: configs,
                        resource: resource,
                        component: innerComponent,
                        record: record,
                        containerClass: component.columns ? `md:col-${12 / component.columns}` : '',
                        formData,
                        setFieldValue,
                        errors
                    })
                ) : (
                    <div key={`form_${index}_${innerComponent.componentName}`}></div>
                )
            )}
        </div>
    );
};

export default GirdLayout;

// Trinity-Vue/src/Layouts/GridLayout.vue
<template>
  <div
    class="p-fluid grid px-0 mx-0 col-12"
    :class="[
      props.component.columnSpan > 0 && props.component.columnSpan < 12
        ? `md:col-${props.component.columnSpan}`
        : '',
    ]"
  >
    <template
      v-for="(innerComponent, index) of props.component.schema"
      :key="`gird_${index}_${innerComponent.componentName}`"
    >
      <component
        :is="innerComponent.componentName"
        :component="innerComponent"
        :containerClass="
          props.component.columns
            ? `md:col-${12 / props.component.columns}`
            : ''
        "
        :form="form"
        :errors="errors"
        :setFieldValue="setFieldValue"
      ></component>
    </template>
  </div>
</template>

<script lang="ts" setup>
import type BaseLayout from "@/Types/Models/BaseLayout";
import type LayoutProps from "@/Types/Props/LayoutProps";
import type BaseField from "@/Types/Models/BaseField";

const props = defineProps<LayoutProps<BaseField | BaseLayout>>();
</script>

<style scoped></style>
